# Generated by Django 4.0.4 on 2022-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcriber',
            field=models.IntegerField(default=0),
        ),
    ]
