# Generated by Django 4.0.4 on 2022-04-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_subcriber'),
        ('user', '0004_alter_user_avatar_alter_user_name'),
    ]

    operations = [
    ]
