# Generated by Django 4.0.4 on 2022-04-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('user', '0008_rename_user_savedvideomodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvideomodel',
            name='saved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.visource'),
        ),
    ]
