# Generated by Django 4.0.4 on 2022-04-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_subcribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribers',
            name='user',
        ),
        migrations.AddField(
            model_name='subcribers',
            name='subcriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
