# Generated by Django 4.0.4 on 2022-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visource',
            name='genres',
            field=models.ManyToManyField(to='base.categorymodel'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='categories',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
