# Generated by Django 4.0.4 on 2022-04-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_visource_genres_remove_visource_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visource',
            old_name='category',
            new_name='genres',
        ),
    ]
