# Generated by Django 4.0.4 on 2022-04-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20220422_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subcriber',
        ),
    ]
