# Generated by Django 4.0.4 on 2022-04-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_savedvideomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedvideomodel',
            old_name='user',
            new_name='author',
        ),
    ]
