# Generated by Django 4.0.4 on 2022-04-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_savedvideomodel_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedvideomodel',
            old_name='author',
            new_name='user',
        ),
    ]
