# Generated by Django 4.0.4 on 2022-04-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repcomment',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comment'),
        ),
    ]
