# Generated by Django 4.0.3 on 2022-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_visource_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='visource',
            name='category',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, null=True),
        ),
    ]
