# Generated by Django 4.0.4 on 2022-04-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_subcribers_user_subcribers_subcriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcribers',
        ),
    ]
