# Generated by Django 4.0.4 on 2022-04-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_category_visource_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='categories',
            new_name='genres',
        ),
    ]
